usage: |
  Apply this to resources which requires authentication by sending a JWT in the Authorization header.
  (This role is automatically applied by the `protectedResource` trait.)

  A description of the required `roles` must be provided.
headers:
  Authorization:
    description: |
      You must authenticate by sending a JWT bearer token in this header.
      You may obtain a token by calling `POST /api/auth`.

      **Required roles:** `<<roles>>`
    required: true
    example: "Authorization: Bearer eyJhbGciOiJIUzI1NiI.eyJzdWIiOiJmZDczYjM5OC04Zj.7s76ONko1DF"
responses:
  401:
    description: |
      Authentication is required to access this resource.
      Either you have not authenticated or your credentials are invalid.
    body:
      examples:
        Missing authentication:
          description: You have not sent an Authorization header in the request.
          value: |
            {
              "errors": [
                {
                  "code": "auth.missingAuthorization",
                  "message": "Authentication is required to access this resource. Authenticate by providing a Bearer token in the Authorization header."
                }
              ]
            }
        Malformed authentication:
          description: |
            The Authorization header of our request is not in the correct format.

            The required format is `Bearer TOKEN` where `TOKEN` is a valid JWT that you obtained by calling `POST /api/auth`.
          value: |
            {
              "errors": [
                {
                  "code": "auth.malformedAuthorization",
                  "message": "The Authorization header is not in the correct format. It should be \"Authorization: Bearer TOKEN\"."
                }
              ]
            }
        Invalid authentication:
          description: The JWT bearer token you have sent in the Authorization header is invalid or has expired.
          value: |
            {
              "errors": [
                {
                  "code": "auth.invalidAuthorization",
                  "message": "The Bearer token supplied in the Authorization header is invalid or has expired."
                }
              ]
            }
