displayName: Account
description: Management of your user account.

# GET /api/me
get:
  description: Retrieve your own user account.
  is:
    - protectedResource:
        roles: none
    - serializableResource:
        onlyExample: "?only=id&only=email"
        exceptExample: "?except=roles&except=updatedAt"
  responses:
    200:
      description: Your user account was successfully retrieved.
      body:
        type: User
        example: |
          HTTP/1.1 200 OK
          Content-Type: application/json

          {
            "active": true,
            "createdAt": "2000-01-01T16:30:00.123Z",
            "email": "jdoe@example.com",
            "emailVerified": true,
            "emailVerifiedAt": "2000-01-01T16:32:00.123Z",
            "firstName": "John",
            "id": "10d38b2c-b7ed-41de-986c-bff87031291e",
            "lastName": "Doe",
            "provider": "local",
            "providerId": "jdoe@example.com",
            "providerData": {},
            "roles": [
              "admin"
            ],
            "updatedAt": "2000-02-03T17:00:00.123Z",
            "updatedBy": "2fdf5620-82d3-48ef-8694-7128194ee929"
          }
