type: object
properties:
  email:
    type: string
    description: The email address associated with the user account.
    required: false
  firstName:
    type: string
    description: The user's first name.
  lastName:
    type: string
    description: The user's last name.
