#%RAML 1.0
---
title: BioPocket
baseUri: https://biopocket.ch/api
version: 1
mediaType: application/json
documentation:
  - !include raml/api-errors.raml

traits:
  authenticatedResource: !include raml/traits/authenticated-resource.raml
  identifiableResource: !include raml/traits/identifiable-resource.raml
  jsonConsumer: !include raml/traits/json-consumer.raml
  paginatedResource: !include raml/traits/paginated-resource.raml
  protectedResource: !include raml/traits/protected-resource.raml
  resourceWithInclusion: !include raml/traits/resource-with-inclusion.raml
  serializableResource: !include raml/traits/serializable-resource.raml

types:

  # Generic types
  geoJsonPoint: !include raml/types/geojson-point.raml
  url: !include raml/types/url.raml
  validationErrors: !include raml/types/validation-errors.raml

  # API resources
  Action: !include actions/actions.model.raml
  ActionPartial: !include actions/actions.model.partial.raml
  Auth: !include auth/auth.model.raml
  AuthPost: !include auth/auth.model.post.raml
  Location: !include locations/locations.model.raml
  LocationWrite: !include locations/locations.model.write.raml
  Registration: !include registrations/registrations.model.raml
  RegistrationWrite: !include registrations/registrations.model.write.raml
  Theme: !include themes/themes.model.raml
  User: !include users/users.model.raml
  UserCommon: !include users/users.model.common.raml
  UserWrite: !include users/users.model.write.raml

# Routes
/actions: !include actions/actions.api.raml
/auth: !include auth/auth.api.raml
/locations: !include locations/locations.api.raml
/me: !include users/users.me.raml
/registrations: !include registrations/registrations.api.raml
/themes: !include themes/themes.api.raml
/users: !include users/users.api.raml
