title: API Error codes
content: |
  * `auth.invalidAuthorization` - The authentication failed due to credentials being invalid or expired.
  * `auth.forbidden` - You don't have authorization to access the requested resource.
  * `auth.malformedAuthorization` - The authentication failed due to credentials having unexpected values or format.
  * `auth.missingAuthorization` - THe authentication failed due to missing credentials in the request.
  * `method.notAllowed` - The resource you tried to access does not support the used HTTP method.
  * `record.notFound` - The record you tried to retrieve does not exist or you don't have authorization to access it.
  * `resource.notFound` - There is no resource available for this URL and HTTP method.