language: node_js
node_js:
  - 8
  - 10
addons:
  postgresql: 9.6
services:
  - postgresql
env:
  - IMAGES_BASE_URL=http://example.com/travis MAIL_HOST=example.com MAIL_PORT=25 MAIL_SECURE=false MAIL_USERNAME=jdoe MAIL_PASSWORD=secret MAIL_FROM_ADDRESS=john.doe@example.com NODE_ENV=test SESSION_SECRET=secret
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install postgresql-9.6-postgis-2.3
before_script:
  - psql -U postgres -c 'create database biopocket;'
  - psql -U postgres -c 'create extension postgis;' biopocket
  - psql -U postgres -c 'create extension "uuid-ossp";' biopocket
  - npm run migrate:test
script:
  - npm test
  - npm run lint
after_success:
  - npm run test:coveralls
notifications:
  slack:
    secure: f62SPeU6N4p/H7c/ujehcgB2Pdz2qjLb8G14cMf39N1/MkpDHnHQNMOucRckgnbE6XB0wDVkhcs16/Ksx6mVIelZxAMFkSl89UoLLjjpegnRFrbJYONlAsBsF7vZ9yvwALCGqaxlipnZzq6h9+c2JHoEFjqnTB50x1dJ5G9R4hefVulFadwzVhNJGjJmdUYNFaA248xY1ztgRDR9VOBdQ7bAbl8HK9fzcl79LwF9fkwoe1pJdy6L7mU8XpkjNhj3b4wpt5BZDMHh+XFhDRAKmE0FVJRaN8eySExpcnzj3YGdS0uLMVBbNr2p99Bo5+AU4r72yU7T67cFLQ3yrd/PJPeeOnmZfnd8PYvaCN9tA7n+wX65QKIOqctwKkqO/kJIHpHsLO0cdc+MEy4iV7i6nAxDB2WKmv13pLUgPHnDThW4qpPX81gQRAkK9mJIFP4wRyvHV/Eshzx38daGIn5awiRhXNI/uxDFqpceLC8c0/7z1FkMnAlVfM59wWwMetxqj9xpyFuiuv2lmaADbCbgid/eDuPkTo9j4Ef+o+ugDeSmYCF9XmGqgpA0fqMasICl5eWoCxbaxc/finopQc0zNpyK8myrv0WLTwur2UFDnF6IjCYehcNwHBS243W05HrzCmD+VccWvybf4gwpqXpMkdHi9LEfhbfZF3uuJXrOP8k=
