type: LocationWrite
properties:
  id:
    type: string
    description: A unique ID identifying the location.
    required: false
  createdAt:
    type: datetime
    description: The time at which the location was created.
    required: false
  updatedAt:
    type: datetime
    required: false
    description: The time at which the location was last updated.
