type: Action
properties:
  theme:
    type: Theme
    description: |
      The complete action's theme object.

      **Note that this property is only present when the `include` query parameter is present with a value of `theme`.**
    required: false