displayName: Actions
description: Management of BioPocket actions.

# GET /api/actions
get:
  description: List actions.
  is:
    - paginatedResource
    - resourceWithInclusion:
        resourceName: action
        inclusions: theme
        inclusionExamples:
          Include only one relation:
            value: ?include=theme
  responses:
    200:
      description: The actions were successfully listed.
      body:
        type: ActionPartial[]
        examples:
          Without any parameters:
            value: |
              HTTP/1.1 200 OK
              Content-Type: application/json

              [
                {
                  "id": "0c51ffa1-3997-46f3-ae84-5c3102f9b520",
                  "themeId": "f8af36b4-dc30-4e34-a0d3-9c25cc125f0e",
                  "title": "Afzoklac delbe ova.",
                  "description": "Co su tobifa uhwir ugjah novufzed oweilati duk vuuwa livarave woh iwsu waere juugo.",
                  "createdAt": "2018-06-01T11:40:54.231Z",
                  "updatedAt": "2018-06-01T11:40:54.231Z"
                },
                {
                  "id": "02959f49-da0d-452b-9208-300b5307ab9a",
                  "themeId": "f8af36b4-dc30-4e34-a0d3-9c25cc125f0e",
                  "title": "Ajve aniro eveda.",
                  "description": "Zernaku tungud aw vevu irkerzil livi fansi se sum oj begib buzoceti mavodfot.",
                  "createdAt": "2018-06-01T11:40:54.230Z",
                  "updatedAt": "2018-06-01T11:40:54.230Z"
                }
              ]
          With an include param (set to "theme"):
            value: |
              HTTP/1.1 200 OK
              Content-Type: application/json

              [
                {
                  "id": "0c51ffa1-3997-46f3-ae84-5c3102f9b520",
                  "themeId": "f8af36b4-dc30-4e34-a0d3-9c25cc125f0e",
                  "theme": {
                    "id": "f8af36b4-dc30-4e34-a0d3-9c25cc125f0e",
                    "title": "Ajkivjo zu numcomoj.",
                    "description": "Obaraga burjeti edisujav arkohiw jeuc suveztu ukbe cap efaulepor kuvojpo ku giftazihe. Vubad tulil id eripa lufcogtav irate nukeik oti cebar luden hi fifapi sen. Ko le wujegim doah keskekew akolamha ehjucof ih dafesul hobzuc ah go. Ki refle oreub zovukos ub siric ni cez po calejocu gav pez vavhaen.",
                    "photoUrl": "http://example.com/evuethaz.jpg",
                    "source": "Revbug rutihi uza.",
                    "createdAt": "2018-06-01T11:40:54.126Z",
                    "updatedAt": "2018-06-01T11:40:54.126Z"
                  },
                  "title": "Afzoklac delbe ova.",
                  "description": "Co su tobifa uhwir ugjah novufzed oweilati duk vuuwa livarave woh iwsu waere juugo.",
                  "createdAt": "2018-06-01T11:40:54.231Z",
                  "updatedAt": "2018-06-01T11:40:54.231Z"
                },
                {
                  "id": "02959f49-da0d-452b-9208-300b5307ab9a",
                  "themeId": "f8af36b4-dc30-4e34-a0d3-9c25cc125f0e",
                  "theme": {
                    "id": "f8af36b4-dc30-4e34-a0d3-9c25cc125f0e",
                    "title": "Ajkivjo zu numcomoj.",
                    "description": "Obaraga burjeti edisujav arkohiw jeuc suveztu ukbe cap efaulepor kuvojpo ku giftazihe. Vubad tulil id eripa lufcogtav irate nukeik oti cebar luden hi fifapi sen. Ko le wujegim doah keskekew akolamha ehjucof ih dafesul hobzuc ah go. Ki refle oreub zovukos ub siric ni cez po calejocu gav pez vavhaen.",
                    "photoUrl": "http://example.com/evuethaz.jpg",
                    "source": "Revbug rutihi uza.",
                    "createdAt": "2018-06-01T11:40:54.126Z",
                    "updatedAt": "2018-06-01T11:40:54.126Z"
                  },
                  "title": "Ajve aniro eveda.",
                  "description": "Zernaku tungud aw vevu irkerzil livi fansi se sum oj begib buzoceti mavodfot.",
                  "createdAt": "2018-06-01T11:40:54.230Z",
                  "updatedAt": "2018-06-01T11:40:54.230Z"
                  }
                }
              ]
/{id}:
  uriParameters:
    id:
      description: The unique ID of the action.
      type: string

  # GET /api/actions/:id
  get:
    description: Retrieve a single action with all of its relations included.
    is:
      - identifiableResource:
          name: action
      - serializableResource:
          onlyExample: "?only=id&only=title&only=theme.title"
          exceptExample: "?except=theme&except=description"
    responses:
      200:
        description: The action was successfully retrieved.
        body:
          type: Action
          example: |
            HTTP/1.1 200 OK
            Content-Type: application/json

            {
              "id": "5552d4f4-2216-4046-bade-0624034868ea",
              "themeId": "857ee0cb-6ba7-4cb7-a91c-dd4a0e0ae9aa",
              "theme": {
                  "id": "857ee0cb-6ba7-4cb7-a91c-dd4a0e0ae9aa",
                  "title": "Cizibni pehov vi safop oveum.",
                  "description": "Gogannaw wupi malje nadfi ifililcuc ci sevviflow aglus kuglotaj sih nevkupad rev hole ole pe. Asniz uwuop fu didimo casub ilnirhim sefilro tapubcu lajecoh tugu kadipli sagejdu ladnih cubul big tehebku. Eko lopo li nudimo muec wemuhug na dewawnez kahas ruvti cipoco pifpo sahe wuvulega okeda amemi. Eceka wo du simibdu towen okvusnec revostus vaoggak umilo ovedume kaib si.",
                  "photoUrl": "http://example.com/moaba.jpg",
                  "source": "Kisgabvo cozekda ulicukzal.",
                  "createdAt": "2018-05-22T11:20:23.337Z",
                  "updatedAt": "2018-05-22T11:20:23.337Z"
              },
              "title": "Ace penvot ishempez.",
              "description": "Rein ce rin poso abvu it nillu ne rikmetwi jo ko pa tipkagim gorhiviz.",
              "createdAt": "2018-05-23T08:22:42.158Z",
              "updatedAt": "2018-05-23T08:22:42.158Z"
            }
