type: object
properties:
  id:
    type: string
    description: A unique ID identifying the action.
  themeId:
    type: string
    description: A unique ID identifying the action's theme.
  title:
    type: string
    description: The action's title.
    minLength: 1
    maxLength: 40
  description:
    type: string
    description: A small text desribing what the action is about.
    minLength: 1
    maxLength: 255
  photoUrl:
    type: string
    description: The URL to the picture illustrating the action.
  createdAt:
    type: datetime
    description: The time at which the action was created.
  updatedAt:
    type: datetime
    description: The time at which the action was last updated.
  theme:
    type: Theme
    description: |
      The complete action's theme object.
