type: object
properties:
  id:
    type: string
    description: A unique ID identifiying the theme.
  createdAt:
    type: datetime
    description: The time at which the theme was created.
  updatedAt:
    type: datetime
    description: The time at which the theme was last updated.