type: object
properties:
  id:
    type: string
    description: A unique ID identifiying the theme.
  title:
    type: string
    minLength: 1
    maxLength: 40
    description: The theme's title
  description:
    type: string
    description: The theme's description.
  photoUrl:
    type: string
    description: The URL to the picture illustrating the theme.
  source:
    type: string
    description: A description of the source that provided the picture.
    required: false
  createdAt:
    type: datetime
    description: The time at which the theme was created.
  updatedAt:
    type: datetime
    description: The time at which the theme was last updated.
