type: RegistrationWrite
properties:
  id:
    type: string
    description: A unique ID identifying the registration.
  createdAt:
    type: datetime
    description: The time at which the registration was created.
  updatedAt:
    type: datetime
    description: The time at which the registration was last updated.
