type: object
properties:
  firstname:
    type: string
    description: The first name of the person who registered.
  lastname:
    type: string
    description: The last name of the person who registered.
  email:
    type: string
    description: The e-mail address of the person who registerd.
